  create-issue-on-failure:

    needs: test-run
    
    permissions:
      issues: write
    
    if: always() && failure() 
    uses: ./.github/workflows/create-failure-issue.yml 
    with:
      title: "Automated workflow failure issue for commit ${{ github.sha }}"
      body: "This issue was automatically created by the GitHub Action workflow ** ${{ github.workflow }} **"  
